# path to the task data directory
data_dir: null

# either provide a path to a plaintext file describing the task
desc_file: null
# or provide the task goal (and optionally evaluation information) as arguments
goal: null
eval: null

log_dir: logs
log_level: INFO
workspace_dir: workspaces

# whether to unzip any archives in the data directory
preprocess_data: True
# whether to copy the data to the workspace directory (otherwise it will be symlinked)
# copying is recommended to prevent the agent from accidentally modifying the original data
copy_data: True

exp_name: null # a random experiment name will be generated if not provided

# settings for code execution
exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: False

# agent hyperparams
agent:
  # how many improvement iterations to run
  steps: 20
  # total time available to agent
  time_limit: 86400 # 24 hrs (purely informational, implementation is user's resp)
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 5
  # whether to instruct the agent to generate a prediction function
  expose_prediction: False
  # whether to provide the agent with a preview of the data
  data_preview: True
  # whether to convert system messages into user messages
  convert_system_to_user: False
  # whether to obfuscate that we're doing kaggle
  obfuscate: False

  # LLM settings for coding
  code:
    model: gpt-4-turbo
    temp: 0.5

  # LLM settings for evaluating program output / tracebacks
  feedback:
    model: gpt-4-turbo
    temp: 0.5

  # hyperparameters for the tree search
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 5


# EDA configuration
eda:
  enable: False
  sample_max_rows: 30000
  sample_rate: 0.10
  sample_seed: 42
  max_columns: 80
  top_values_k: 10
  top_tokens_k: 20
  top_ngrams_k: 20
  top_corr_k: 30
  top_assoc_k: 30
  redaction_enable: True
  pii_hash_salt: AIDE_DEFAULT_SALT
  pii_rules: [email, phone, ip, cc]
  artifacts_subdir: artifacts/eda
  cache_by_hash: True
  target_column: null
  compact:
    enable: True
    mode: compact   # {compact|ultra}
    token_budget_compact: 900
    token_budget_ultra: 450
